stages:
  - test

.test:
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - python --version

  script:
    - pip install numpy
    - pip install cython
    - python setup.py install
    - python -m unittest xqml.tests.test_xqml

# test-3.6:
#   extends: .test
#   stage: test
#   image: python:3.6

# test-3.7:
#   extends: .test
#   stage: test
#   image: python:3.7

test-3.8:
  extends: .test
  stage: test
  image: python:3.8

test-3.9:
  extends: .test
  stage: test
  image: python:3.9
